import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://download.logo.wine/logo/Hulu/Hulu-Logo.wine.png" />
      </Head>


        <Header />

    </div>
  )
}
